version: '3.8'
services:
    mongodb:
        image : mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pw
        volumes:
            - /home/alex/git/data-extraction-for-reddit/mongodb/database:/data/db
        restart: unless-stopped
